// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAmEgFyKtoCNsyBDNqMyyVOH5zP_pRafd4',
    appId: '1:986784441321:web:689287b07e85902a12a178',
    messagingSenderId: '986784441321',
    projectId: 'at-your-service-1cb5a',
    authDomain: 'at-your-service-1cb5a.firebaseapp.com',
    storageBucket: 'at-your-service-1cb5a.firebasestorage.app',
    measurementId: 'G-3CQZHLY6QF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCS21B-W3mGo0kOEm8NZ_6AxEOjCKCkQfQ',
    appId: '1:986784441321:android:8bab072ac20d97f512a178',
    messagingSenderId: '986784441321',
    projectId: 'at-your-service-1cb5a',
    storageBucket: 'at-your-service-1cb5a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAN0Ke2tUAruaeeTkaBzO8Yq3q_XEQExbY',
    appId: '1:986784441321:ios:68e54701f5fef2b212a178',
    messagingSenderId: '986784441321',
    projectId: 'at-your-service-1cb5a',
    storageBucket: 'at-your-service-1cb5a.firebasestorage.app',
    iosBundleId: 'com.example.atYourService',
  );
}
